# Generated by Django 4.2 on 2023-06-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(upload_to=''),
        ),
    ]
