# Generated by Django 4.2 on 2023-06-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('user_id', 'blog_post')},
        ),
    ]
